### ISSUE TITLE
Provide description in pom.xml

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-jnosql#88]
The maven description is used to enrich the Quarkus metadata, `quarkus-extension.yaml`. At the moment, because the jnosql pom doesn't have a description, it inherits the parent description. That then gets published on https://quarkus.io/extensions/io.quarkiverse.jnosql/quarkus-jnosql-document-mongodb/. 

<img width="1140" alt="image" src="https://github.com/quarkiverse/quarkus-jnosql/assets/11509290/26822554-74c0-4e33-b576-dba459df72b5">

**Comment by amoscatelli** [comment]
Thx @otaviojava
